services:
    app:
        build:
            context: .docker/dev
        environment:
            APP_ENV: "prod"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            PHP_XDEBUG_IDEKEY: "PHPSTORM"
            MAILER_URL: "smtp://mailhog:1025"
        volumes:
            - ./:/app:delegated
            - ./.docker/dev/php.ini:/usr/local/etc/php/php.ini:delegated
            - ./.docker/dev/php.ini:/usr/local/etc/php/cli/php.ini:delegated
        ports:
            - "127.0.0.1:8080:80"  # 仅本地访问，通过宿主机 Nginx 反向代理
        depends_on:
            mysql:
                condition: service_healthy  # 等待 MySQL 健康检查通过
        networks:
            - sylius

    mysql:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        volumes:
            - mysql-data:/var/lib/mysql  # 持久化数据库数据
        networks:
            - sylius
        # 添加健康检查，确保 MySQL 完全启动后再启动 app 容器
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmysql"]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 30s

#    postgres:
#        image: postgres:13-alpine
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - ${POSTGRES_PORT:-5432}:5432
#        networks:
#            - sylius

    mailhog:
        image: mailhog/mailhog
        ports:
            - ${MAILHOG_PORT:-8025}:8025 # UI
        networks:
            - sylius

    blackfire:
        image: blackfire/blackfire:2
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ~
            BLACKFIRE_SERVER_TOKEN: ~
            BLACKFIRE_CLIENT_ID: ~
            BLACKFIRE_CLIENT_TOKEN: ~
            BLACKFIRE_DISABLE_LEGACY_PORT: 1
        ports:
            - ${BLACKFIRE_PORT:-8307}:8307
        networks:
            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    mysql-data:
        driver: local