name: 🐛 Bug Report
description: ⚠️ NEVER report security issues, read https://docs.sylius.com/the-book/contributing/contributing-code/security-issues instead
labels: Potential Bug

body:
    - type: input
      id: affected-versions
      attributes:
          label: Sylius version(s) affected
          placeholder: x.y.z
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A clear and concise description of the problem
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce
          description: |
              ⚠️ This is the most important part of the report ⚠️
              We’ll have a much better chance of helping if we can easily reproduce the issue.
              Please take a moment to share some code or configuration details to make it easier for us to investigate and fix the problem.
      validations:
          required: true
    - type: textarea
      id: possible-solution
      attributes:
          label: Possible Solution
          description: |
              Optional: only if you have suggestions on a fix/reason for the bug
              Don't hesitate to create a pull request with your solution, it helps get faster feedback.
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: "Optional: any other context about the problem: log messages, screenshots, etc."
